### ISSUE TITLE
Errors while setting up stripe

### ISSUE THREAD

**Issue by afyacy** [afyacy/sharedemo#1]
The app started behaving untypical since I begun with the stripe API integration. I will appreciate any contribution. Thank you.

**Comment by jeremiahlukus** [comment]
Can you describe this untypical behavior?

**Comment by afyacy** [comment]
After signing in, different links are supposed to appear on the nav bar(a dropdown menu with sublinks to edit or logout) but they remain the same.

**Comment by jeremiahlukus** [comment]
Hm, this worked before you tried to implement stripe?

**Comment by afyacy** [comment]
Adding order history on 11th June

**Comment by afyacy** [comment]
Yea, or did do something earlier to affect its behaviour but recognized it
after implementing stripe...

**Comment by jeremiahlukus** [comment]
I recommend going back to rewatch the videos. There are several things that were messed up when I ran it on my local server. I could not sign-up I had to use the console. You should go back and take your time.

**Comment by jeremiahlukus** [comment]
If you have a certain block of code or a file that is causing you trouble then I can help. I do not want to rob you of learning and do this for you.

**Comment by afyacy** [comment]
Alright, Thank you.

**Comment by jeremiahlukus** [comment]
If things are too bad just do git reset to get you back to where your code works. The bad things about the course is that does not have tests to see if you broke your code doing something else. Its a good course to just jump into Rails though. Always check your code to make sure everything works. Never start working on something else while your code doesn't work. These issues will stack up making it extremely hard to fix. Programming is about fixing many small problems, not one big one.
